---
baseurl: "http://niloc.io/"
languageCode: "en-us"
title: "Musings of a Developer"
theme: "hugo-zen"
metaDataFormat: "yaml"
author:
  name: "Colin Hoernig"
params:
  gravatarHash: "15cb4683f9aa1f015998d230b61b0ef7"
  copyright: "Colin Hoernig.  Share information freely."
  twitter: "https://twitter.com/colinhoernig"
  github: "https://github.com/colinhoernig"
  email: "me@niloc.io"
  linkedin: "https://linkedin.com/in/colinhoernig"
